// apps/web/components/motion-core/lava-lamp/LavaLamp.svelte

<script lang="ts">
import type { ComponentProps } from "svelte";
import type Scene from "./LavaLampScene.svelte";

type SceneProps = ComponentProps<typeof Scene>;

interface Props {
  /**
   * Additional CSS classes for the container.
   */
  class?: string;
  /**
   * Base color of the lava blobs.
   * @default "#18181b"
   */
  color?: SceneProps["color"];
  /**
   * Color of the fresnel effect.
   * @default "#ff6900"
   */
  fresnelColor?: SceneProps["fresnelColor"];
  /**
   * Fresnel power for the edge lighting effect.
   * @default 3.0
   */
  fresnelPower?: SceneProps["fresnelPower"];
  /**
   * Base radius of the blobs.
   * @default 1
   */
  radius?: SceneProps["radius"];
  /**
   * Smoothness of the blob blending (metaball effect).
   * @default 0.1
   */
  smoothness?: SceneProps["smoothness"];
  /**
   * Speed of the lava animation.
   * @default 1.0
   */
  speed?: SceneProps["speed"];
  [key: string]: unknown;
}

let {
  class: className = "",
  color = "#18181b",
  fresnelColor = "#ff6900",
  speed = 1.0,
  fresnelPower = 3.0,
  radius = 1,
  smoothness = 0.1,
  ...rest
}: Props = $props();

const dpr = typeof window === "undefined" ? 1 : window.devicePixelRatio;
</script>

<div class={cn("relative h-full w-full overflow-hidden", className)} {...rest}>
	<div class="absolute inset-0 z-0">
		<Canvas {dpr} toneMapping={NoToneMapping}>
			<Scene
				{color}
				{fresnelColor}
				{speed}
				{fresnelPower}
				{radius}
				{smoothness}
			/>
		</Canvas>
	</div>
</div>

// apps/web/components/motion-core/lava-lamp/lava-lamp.tsx
import { Canvas } from "@react-three/fiber";
import { NoToneMapping } from "three";
import { cn } from "@/lib/utils";
import { LavaLampMesh } from "./lava-lamp-scene";

type LavaLampProps = {
  className?: string;
  color?: string;
  fresnelColor?: string;
  fresnelPower?: number;
  radius?: number;
  smoothness?: number;
  speed?: number;
  [key: string]: unknown;
};

export default function LavaLamp({
  className = "",
  color = "#18181b",
  fresnelColor = "#ff6900",
  speed = 1.0,
  fresnelPower = 3.0,
  radius = 1,
  smoothness = 0.1,
  ...rest
}: LavaLampProps) {
  const dpr = typeof window === "undefined" ? 1 : window.devicePixelRatio;

  return (
    <div
      className={cn("relative h-full w-full overflow-hidden", className)}
      {...rest}
    >
      <div className="absolute inset-0 z-0">
        <Canvas dpr={dpr} gl={{ antialias: false, toneMapping: NoToneMapping }}>
          <LavaLampMesh
            color={color}
            fresnelColor={fresnelColor}
            fresnelPower={fresnelPower}
            radius={radius}
            smoothness={smoothness}
            speed={speed}
          />
        </Canvas>
      </div>
    </div>
  );
}
